Map<String, Map<String, String>> packageLanguages = {
  'no_internet_connection' : {
    'ar' : 'لا يوجد اتصال بالإنترنت',
    'en' : 'No internet connection',
    'es' : 'Sin conexión a internet',
    'pt' : 'Sem conexão à internet',
    'de' : 'Keine Internetverbindung',
    'fr' : 'Pas de connexion internet',
    'it' : 'Nessuna connessione a internet',
    'ru' : 'Нет подключения к интернету',
    'ch' : '没有网络连接',
    'ko' : '인터넷 연결 없음',
    'ja' : 'インターネット接続なし',
    'hi' : 'इंटरनेट कनेक्शन नहीं है',
    'fa' : 'بدون اتصال به اینترنت',
  },
  'try_again' : {
    'ar' : 'حاول مرة أخرى',
    'en' : 'Try again',
    'es' : 'Inténtalo de nuevo',
    'pt' : 'Tente novamente',
    'de' : 'Erneut versuchen',
    'fr' : 'Réessayez',
    'it' : 'Riprova',
    'ru' : 'Попробуйте еще раз',
    'ch' : '再试一次',
    'ko' : '다시 시도',
    'ja' : 'もう一度試す',
    'hi' : 'पुनः प्रयास करें',
    'fa' : 'برای امتحان مجدد',
  },
  'error_in_connection' : {
    'ar' : 'خطأ في الاتصال',
    'en' : 'Error in connection',
    'es' : 'Error en la conexión',
    'pt' : 'Erro na conexão',
    'de' : 'Fehler bei der Verbindung',
    'fr' : 'Erreur de connexion',
    'it' : 'Errore di connessione',
    'ru' : 'Ошибка в соединении',
    'ch' : '连接错误',
    'ko' : '연결 오류',
    'ja' : '接続エラー',
    'hi' : 'संपर्क त्रुटि',
    'fa' : 'خطای اتصال',
  },
  'no_places_found' : {
    'ar' : 'لم يتم العثور على أماكن',
    'en' : 'No places found',
    'es' : 'No se encontraron lugares',
    'pt' : 'Nenhum lugar encontrado',
    'de' : 'Keine Orte gefunden',
    'fr' : 'Aucun lieu trouvé',
    'it' : 'Nessun luogo trovato',
    'ru' : 'Места не найдены',
    'ch' : '未找到任何地点',
    'ko' : '장소를 찾을 수 없습니다',
    'ja' : '場所が見つかりません',
    'hi' : 'कोई स्थान नहीं मिला',
    'fa' : 'هیچ مکانی یافت نشد',
  },
  'search_for_place' : {
    'ar' : 'ابحث عن مكان',
    'en' : 'Search for place',
    'es' : 'Buscar lugar',
    'pt' : 'Pesquisar por lugar',
    'de' : 'Suche nach Ort',
    'fr' : 'Rechercher un lieu',
    'it' : 'Cerca per luogo',
    'ru' : 'Поиск места',
    'ch' : '搜索地点',
    'ko' : '장소 검색',
    'ja' : '場所を検索',
    'hi' : 'स्थान खोज',
    'fa' : 'جستجوی مکان',
  }
};

/// Supported languages
/*
    'ar' : '',
    'en' : '',
    'es' : '',
    'pt' : '',
    'de' : '',
    'fr' : '',
    'it' : '',
    'ru' : '',
    'ch' : '',
    'ko' : '',
    'ja' : '',
    'hi' : '',
    'fa' : '',
 */
